In [ ]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')

In [1]:
df.head()

NameError: name 'df' is not defined

Creating arrays

In [6]:
np.zeros(5)
np.ones(5)
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [12]:
a = np.array([1, 2, 3, 4, 5])

In [13]:
a[2] = 10

In [14]:
a[2]

np.int64(10)

In [15]:
a

array([ 1,  2, 10,  4,  5])

In [16]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
np.linspace(0, 1, 9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

Multi-dimensional arrays

In [20]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
n = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [27]:
n[0, 1] = 20

In [28]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [29]:
n[2] = [1, 1, 1]

In [32]:
n[2]

array([1, 1, 1])

In [31]:
n[:, 1]

array([20,  5,  1])

Randomly generated arrays

In [33]:
np.random.rand(5, 2)

array([[0.24664263, 0.32086576],
       [0.23387841, 0.65446154],
       [0.17160243, 0.10471577],
       [0.42823221, 0.48762855],
       [0.49175806, 0.09803543]])

In [36]:
np.random.seed(42)
np.random.randn(5, 2)

array([[ 0.49671415, -0.1382643 ],
       [ 0.64768854,  1.52302986],
       [-0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473],
       [-0.46947439,  0.54256004]])

In [41]:
np.random.randint(low = 1, high = 100, size = (5, 2))

array([[60, 21],
       [33, 76],
       [58, 22],
       [89, 49],
       [91, 59]])

In [42]:
n * 2

array([[ 2, 40,  6],
       [ 8, 10, 12],
       [ 2,  2,  2]])

In [47]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [48]:
n >= 1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [50]:
b = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [52]:
n[n >= b]

array([ 1, 20,  3,  4,  5,  6])

In [55]:
n.sum()

np.int64(42)

Vector-vector multiplication

In [56]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0.0

    for i in range(n):
        result += u[i] * v[i]
    return result

In [61]:
u = np.array([1, 2, 3])

In [71]:
v = np.array([4, 5, 6, 7])

In [63]:
vector_vector_multiplication(u, v)

np.float64(32.0)

In [64]:
u.dot(v)

np.int64(32)

Matrix-vector multiplication = Dot product b/w every matrix row and vector = m*n * n*1 = m*1
Row number from matrix, column number from vector (1)

In [87]:
U = np.array([[2, 4, 5, 6], 
              [1, 2, 1, 2], 
              [3, 1, 2, 1]])

In [68]:
U.shape

(3, 4)

In [79]:
def matrix_v_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
        
    return result

In [80]:
matrix_v_multiplication(U, v)

array([100.,  34.,  36.])

In [81]:
U.dot(v)

array([100,  34,  36])

Matrix-matrix multiplication = Dot product b/w every matrix 1 row and every vector (column) in matrix 2
Row number from matrix 1, column number from matrix 2

In [84]:
V = np.array([[1, 1, 1], 
              [0, 0, 0], 
              [2, 2, 2], 
              [0, 1, 2]])

In [95]:
square_m = U.dot(V)

Identity matrix. U * I = U (acts like number 1)

In [90]:
I = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

In [91]:
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [92]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Matrix Inverse (only exists for square matrices)

In [101]:
random_matrix = np.array([[1, 45, 3], [34, 452, 11], [3, 6, 90]])

In [102]:
MI = np.linalg.inv(random_matrix)

In [103]:
MI

array([[-0.41000636,  0.04070384,  0.00869197],
       [ 0.03055816, -0.00081771, -0.00091866],
       [ 0.01162967, -0.00130228,  0.01088262]])

Pandas

In [ ]:
df2 = pd.DataFrame(data, columns = columns) #data = list of lists, columns = list of columns)
df3 = pd.DataFrame(data) #if data = list of dictionaries, columns are given by keys

In [105]:
df.head(2)

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.0
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.0

In [106]:
df.Laptop

0       ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...
1       Alurin Go Start Intel Celeron N4020/8GB/256GB ...
2       ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...
3       MSI Katana GF66 12UC-082XES Intel Core i7-1270...
4       HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...
                              ...
2155    Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...
2156    Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...
2157    Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...
2158    Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...
2159    Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...
Name: Laptop, Length: 2160, dtype: str

In [109]:
df[['Laptop', 'Status', 'Brand']]

                                                 Laptop       Status   Brand
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP
...                                                 ...          ...     ...
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer

[2160 rows x 3 columns]

In [6]:
df['id'] = 0

In [7]:
df.head()

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price,id
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00,0
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00,0
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00,0
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00,0
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01,0

In [8]:
del df['id']

In [9]:
df.head()

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01

Index

In [11]:
df.index

RangeIndex(start=0, stop=2160, step=1)

Location(loc)

In [4]:
df.loc[[1, 2]]

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.0
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.0

In [5]:
df.iloc[[1, 2, 3]]

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.0
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.0
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.0

In [9]:
df.reset_index(drop = True)

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01
...,...,...,...,...,...,...,...,...,...,...,...,...
2155,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,16,1000,SSD,RTX 3060,17.3,No,2699.99
2156,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,16,1000,SSD,RTX 3070,17.3,No,2899.99
2157,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,32,1000,SSD,RTX 3080,17.3,No,3399.99
2158,Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...,Refurbished,Razer,Book,Intel Evo Core i7,16,1000,SSD,NaN,13.4,Yes,1899.99
2159,Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...,Refurbished,Razer,Book,Intel Evo Core i7,16,256,SSD,NaN,13.4,Yes,1699.99

Element-wise operations

In [10]:
df['Final Price'] / 2

0        504.500
1        149.500
2        394.500
3        599.500
4        334.505
          ...
2155    1349.995
2156    1449.995
2157    1699.995
2158     949.995
2159     849.995
Name: Final Price, Length: 2160, dtype: float64

Filtering

In [11]:
df['Screen'] >= 15.6

0        True
1        True
2        True
3        True
4        True
        ...
2155     True
2156     True
2157     True
2158    False
2159    False
Name: Screen, Length: 2160, dtype: bool

In [16]:
df[df['Screen'] >= 15.6]

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01
...,...,...,...,...,...,...,...,...,...,...,...,...
2153,Razer Blade 15 Base Model FHD Intel Core i7-10...,Refurbished,Razer,Blade,Intel Core i7,16,512,SSD,RTX 3070,15.6,No,1583.39
2154,Razer Blade 17 4K 144Hz Intel Core i9-12900H/3...,Refurbished,Razer,Blade,Intel Core i9,32,1000,SSD,RTX 3080,17.3,No,4699.99
2155,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,16,1000,SSD,RTX 3060,17.3,No,2699.99
2156,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,16,1000,SSD,RTX 3070,17.3,No,2899.99
2157,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,32,1000,SSD,RTX 3080,17.3,No,3399.99

In [19]:
df['Model'].str.replace('Ex', 'Sex').str.lower()

0       sexpertbook
1                go
2       sexpertbook
3            katana
4               15s
           ...
2155          blade
2156          blade
2157          blade
2158           book
2159           book
Name: Model, Length: 2160, dtype: str

Summarizing operations

In [21]:
df.describe().round(2)

           RAM  Storage   Screen  Final Price
count  2160.00  2160.00  2156.00      2160.00
mean     15.41   596.29    15.17      1312.64
std       9.87   361.22     1.20       911.48
min       4.00     0.00    10.10       201.05
25%       8.00   256.00    14.00       661.08
50%      16.00   512.00    15.60      1031.95
75%      16.00  1000.00    15.60      1708.97
max     128.00  4000.00    18.00      7150.47

In [22]:
df['CPU'].nunique()

28

In [23]:
df.nunique()

Laptop          2160
Status             2
Brand             27
Model            121
CPU               28
RAM                9
Storage           12
Storage type       2
GPU               44
Screen            29
Touch              2
Final Price     1440
dtype: int64

Missing values

In [25]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

Grouping (SELECT -> FROM -> GROUP_BY

In [30]:
df.groupby('CPU', as_index = False)['Final Price'].mean().sort_values(by='Final Price', ascending=False)

                      CPU  Final Price
5            AMD Radeon 9  5192.110000
22      Intel Evo Core i9  3699.010000
19          Intel Core i9  3350.067340
13           Apple M2 Pro  2860.543077
11           Apple M1 Pro  2703.861429
9             AMD Ryzen 9  2481.034773
12               Apple M2  1911.144643
21      Intel Evo Core i7  1908.773049
18          Intel Core i7  1650.331789
25          Microsoft SQ1  1584.783333
10               Apple M1  1480.049091
20      Intel Evo Core i5  1359.457000
27  Qualcomm Snapdragon 8  1216.780000
8             AMD Ryzen 7  1155.486410
17          Intel Core i5   888.378467
7             AMD Ryzen 5   732.087244
15          Intel Core M3   683.582000
26  Qualcomm Snapdragon 7   577.553333
16          Intel Core i3   532.510769
23          Intel Pentium   504.404000
4            AMD Radeon 5   499.000000
6             AMD Ryzen 3   489.845455
24        Mediatek MT8183   458.000000
1               AMD 3015e   439.826667
3              AMD Athlon   398.828000
2               AMD 3020e   373.530000
14          Intel Celeron   362.505638
0              AMD 3015Ce   327.000000

In [33]:
# This returns a Series where CPU is the index
sorted_series = df.groupby('CPU')['Final Price'].mean().sort_values(ascending=False)
sorted_series

CPU
AMD Radeon 9             5192.110000
Intel Evo Core i9        3699.010000
Intel Core i9            3350.067340
Apple M2 Pro             2860.543077
Apple M1 Pro             2703.861429
AMD Ryzen 9              2481.034773
Apple M2                 1911.144643
Intel Evo Core i7        1908.773049
Intel Core i7            1650.331789
Microsoft SQ1            1584.783333
Apple M1                 1480.049091
Intel Evo Core i5        1359.457000
Qualcomm Snapdragon 8    1216.780000
AMD Ryzen 7              1155.486410
Intel Core i5             888.378467
AMD Ryzen 5               732.087244
Intel Core M3             683.582000
Qualcomm Snapdragon 7     577.553333
Intel Core i3             532.510769
Intel Pentium             504.404000
AMD Radeon 5              499.000000
AMD Ryzen 3               489.845455
Mediatek MT8183           458.000000
AMD 3015e                 439.826667
AMD Athlon                398.828000
AMD 3020e                 373.530000
Intel Celeron             362.505638
AMD 3015Ce                327.000000
Name: Final Price, dtype: float64

Getting the Numpy arrays

In [34]:
df['Final Price'].values

array([1009.  ,  299.  ,  789.  , ..., 3399.99, 1899.99, 1699.99],
      shape=(2160,))

Back to dictionary

In [38]:
orig = df.to_dict(orient='records')
orig[:5]

[{'Laptop': 'ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core i5-1235U/8GB/512GB SSD/15.6"',
  'Status': 'New',
  'Brand': 'Asus',
  'Model': 'ExpertBook',
  'CPU': 'Intel Core i5',
  'RAM': 8,
  'Storage': 512,
  'Storage type': 'SSD',
  'GPU': nan,
  'Screen': 15.6,
  'Touch': 'No',
  'Final Price': 1009.0},
 {'Laptop': 'Alurin Go Start Intel Celeron N4020/8GB/256GB SSD/15.6"',
  'Status': 'New',
  'Brand': 'Alurin',
  'Model': 'Go',
  'CPU': 'Intel Celeron',
  'RAM': 8,
  'Storage': 256,
  'Storage type': 'SSD',
  'GPU': nan,
  'Screen': 15.6,
  'Touch': 'No',
  'Final Price': 299.0},
 {'Laptop': 'ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core i3-1215U/8GB/256GB SSD/15.6"',
  'Status': 'New',
  'Brand': 'Asus',
  'Model': 'ExpertBook',
  'CPU': 'Intel Core i3',
  'RAM': 8,
  'Storage': 256,
  'Storage type': 'SSD',
  'GPU': nan,
  'Screen': 15.6,
  'Touch': 'No',
  'Final Price': 789.0},
 {'Laptop': 'MSI Katana GF66 12UC-082XES Intel Core i7-12700H/16GB/1TB SSD/RTX3050/15.6"',
  'Status': 'New',
  'Brand': 'MSI',
  'Model': 'Katana',
  'CPU': 'Intel Core i7',
  'RAM': 16,
  'Storage': 1000,
  'Storage type': 'SSD',
  'GPU': 'RTX 3050',
  'Screen': 15.6,
  'Touch': 'No',
  'Final Price': 1199.0},
 {'Laptop': 'HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB SSD/15.6"',
  'Status': 'New',
  'Brand': 'HP',
  'Model': '15S',
  'CPU': 'Intel Core i5',
  'RAM': 16,
  'Storage': 512,
  'Storage type': 'SSD',
  'GPU': nan,
  'Screen': 15.6,
  'Touch': 'No',
  'Final Price': 669.01}]